<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core" nsURI="http://example.com/openAPI/core" nsPrefix="openAPI.core">
  <eClassifiers xsi:type="ecore:EClass" name="JSONSchemaSubset" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//JSONDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusiveMaximum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusiveMinimum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxItems" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minItems" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueItems" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enum" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipleOf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="api" eType="#//API" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paramters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schemas" upperBound="-1"
        eType="#//Schema" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responses" upperBound="-1"
        eType="#//Response" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="API" eSuperTypes="#//ParamterDeclaringContext #//ResponseContext #//SchemaDeclaringContext #//JSONPointer #//SecurityContext #//ParameterContext #//ExternalDocsContext #//ResponseDeclaringContext">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="requiredSwaggerVersion correctSwaggerVersion requiredInfoReference requiredPaths"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="requiredSwaggerVersion" value="not self.swagger.oclIsUndefined()"/>
      <details key="requiredInfoReference" value="not self.info.oclIsUndefined()"/>
      <details key="correctSwaggerVersion" value="self.swagger = '2.0'"/>
      <details key="requiredPaths" value="pathsIsSet()"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="API"/>
    </eAnnotations>
    <eOperations name="getRef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return &quot;#&quot;;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="pathsIsSet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return pathsIsSet();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swagger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="info" eType="#//Info" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemes" upperBound="-1"
        eType="#//SchemeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="produces" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paths" upperBound="-1"
        eType="#//Path" unsettable="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" upperBound="-1"
        eType="#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responses" upperBound="-1"
        eType="#//Response" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityDefinitions" upperBound="-1"
        eType="#//SecuritySchema" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" upperBound="-1" eType="#//Tag"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Info">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="requiredTitle requiredAPIVerison"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="requiredTitle" value="not self.title.oclIsUndefined()"/>
      <details key="requiredAPIVerison" value="not self.version.oclIsUndefined()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="termsOfServices" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contact" eType="#//Contact"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="license" eType="#//License"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="License">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="requiredName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="requiredName" value="not self.name.oclIsUndefined()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Path" eSuperTypes="#//ParamterDeclaringContext #//ParameterContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="get" eType="#//Operation"
        containment="true" eOpposite="#//Operation/path"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="put" eType="#//Operation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="post" eType="#//Operation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delete" eType="#//Operation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" eType="#//Operation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="head" eType="#//Operation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patch" eType="#//Operation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//ParamterDeclaringContext #//ResponseContext #//SecurityContext #//ParameterContext #//ExternalDocsContext #//ResponseDeclaringContext">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="oneBodyParameterAllowed oneFormDataParameterAllowed hasUniqueParameters xorFormAndBody requiredResponses"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="oneBodyParameterAllowed" value="self.parameters-> select(e | e.location = ParameterLocation::'_body') -> size() &lt;= 1"/>
      <details key="oneFormDataParameterAllowed" value="self.parameters-> select(e | e.location = ParameterLocation::'_formData') -> size() &lt;= 1"/>
      <details key="hasUniqueParameters" value="self.parameters -> collect(t | Tuple{name : String = t.name,location : ParameterLocation = t.location})->asSet() -> size() = self.parameters -> size()"/>
      <details key="xorFormAndBody" value="(parameters-> select(e | e.location =  ParameterLocation::_'body') -> size()=1 and parameters-> select(e | e.location =  ParameterLocation::_'formData') -> size()=0)&#xD;&#xA;&#x9;or &#xD;&#xA;&#x9;(parameters-> select(e | e.location =  ParameterLocation::_'body') -> size()=0 and parameters-> select(e | e.location =  ParameterLocation::_'formData') -> size()=1)&#xD;&#xA;&#x9;or &#xD;&#xA;&#x9;(parameters-> select(e | e.location =  ParameterLocation::_'body') -> size()=0 and parameters-> select(e | e.location =  ParameterLocation::_'formData') -> size()=0)&#xD;&#xA;&#x9;"/>
      <details key="requiredResponses" value="self.responses -> size() &lt;> 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagReferences" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="produces" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responses" lowerBound="1"
        upperBound="-1" eType="#//Response"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemes" upperBound="-1"
        eType="#//SchemeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deprecated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="#//Path" eOpposite="#//Path/get"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalDocs">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="requiredURL"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="requiredURL" value="not self.url.oclIsUndefined()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//SchemaDeclaringContext #//SchemaContext #//JSONSchemaSubset #//JSONPointer #//ArrayContext">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="requiredName requiredLocation"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="requiredName" value="not name.oclIsUndefined()"/>
      <details key="requiredLocation" value="not location = ParameterLocation::unspecified"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="#//ParameterLocation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowEmplyValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaringContext" eType="#//ParamterDeclaringContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemsDefinition" eSuperTypes="#//JSONSchemaSubset #//ArrayContext"/>
  <eClassifiers xsi:type="ecore:EClass" name="Schema" eSuperTypes="#//JSONSchemaSubset #//SchemaDeclaringContext #//JSONPointer #//ExternalDocsContext">
    <eOperations name="getRef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (getDeclaringContext() instanceof core.API) {&#xD;&#xA;&#x9;return ((core.API) getDeclaringContext()).getRef() + &quot;/definitions/&quot; + getName();&#xD;&#xA;&#x9;} else if (getDeclaringContext() instanceof Schema) {&#xD;&#xA;Schema context = (Schema) getDeclaringContext();&#x9;&#xD;&#xA;if (context.getProperties().contains(this))&#xD;&#xA;&#x9;return context.getRef() + &quot;/properties/&quot; + getName();&#xD;&#xA;else if (context.getItems().equals(this))&#xD;&#xA;&#x9;return context.getRef() + &quot;/items&quot;;&#xD;&#xA;else if (context.getAdditonalProperties().equals(this))&#xD;&#xA;&#x9;return context.getRef() + &quot;/additionalProperties&quot;;&#xD;&#xA;&#x9;&#x9;&#x9;}&#xD;&#xA;&#x9;return &quot;&quot;;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxProperties" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minProperties" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="example" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readOnly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allOf" upperBound="-1"
        eType="#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" eType="#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xml" eType="#//XMLElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additonalProperties" eType="#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaringContext" eType="#//SchemaDeclaringContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Response" eSuperTypes="#//SchemaDeclaringContext #//SchemaContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="headers" upperBound="-1"
        eType="#//Header" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="examples" upperBound="-1"
        eType="#//Example" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaringContext" eType="#//ResponseDeclaringContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Header" eSuperTypes="#//JSONSchemaSubset #//ArrayContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag" eSuperTypes="#//ExternalDocsContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecuritySchema">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SecuritySchemeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="#//APIKeyLocation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flow" eType="#//OAuth2FlowType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorizationUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokenUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="globalName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scopes" upperBound="-1"
        eType="#//SecurityScope" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Example">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mimeType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wrapped" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityScope">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParamterDeclaringContext" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseContext" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SchemaDeclaringContext" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="JSONPointer" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityContext" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityRequirement" upperBound="-1"
        eType="#//SecurityScope"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterContext" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemaContext" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" eType="#//Schema"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalDocsContext" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalDocs" eType="#//ExternalDocs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayContext" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionFormat" eType="#//CollectionFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" eType="#//ItemsDefinition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SchemeType">
    <eLiterals name="http"/>
    <eLiterals name="https" value="1"/>
    <eLiterals name="ws" value="2"/>
    <eLiterals name="wss" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterLocation">
    <eLiterals name="unspecified" literal="unspecified"/>
    <eLiterals name="query" value="1"/>
    <eLiterals name="header" value="2"/>
    <eLiterals name="path" value="3"/>
    <eLiterals name="formData" value="4"/>
    <eLiterals name="body" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionFormat">
    <eLiterals name="unspecified" literal="unspecified"/>
    <eLiterals name="csv" value="1"/>
    <eLiterals name="ssv" value="2"/>
    <eLiterals name="tsv" value="3"/>
    <eLiterals name="pipes" value="4"/>
    <eLiterals name="multi" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OAuth2FlowType">
    <eLiterals name="unspecified" literal="unspecified"/>
    <eLiterals name="implicit" value="1"/>
    <eLiterals name="password" value="2"/>
    <eLiterals name="application" value="3"/>
    <eLiterals name="accessCode" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="APIKeyLocation">
    <eLiterals name="unspecified" literal="unspecified"/>
    <eLiterals name="query" value="1"/>
    <eLiterals name="header" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SecuritySchemeType">
    <eLiterals name="unspecified" literal="unspecified"/>
    <eLiterals name="basic" value="1"/>
    <eLiterals name="apiKey" value="2"/>
    <eLiterals name="oauth2" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JSONDataType">
    <eLiterals name="unspecified" literal="unspecified"/>
    <eLiterals name="integer" value="1"/>
    <eLiterals name="number" value="2"/>
    <eLiterals name="string" value="3"/>
    <eLiterals name="boolean" value="4"/>
    <eLiterals name="object" value="5"/>
    <eLiterals name="array" value="6" literal="array"/>
    <eLiterals name="file" value="8"/>
    <eLiterals name="null" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseDeclaringContext" abstract="true"/>
</ecore:EPackage>
